# Netlify build instructions
[build]
  # Directory to publish (output of the build command)
   command = "expo export --public-url https://your-domain.com/"
  publish = "web-build"

  # Build command to run
  command = "expo export -p web"

# Redirects and rewrites for single-page application (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
